### ISSUE TITLE
CR-Beeinflussung durch Maschinen

### ISSUE THREAD

**Issue by mfloto** [red-life-project/red-life#44]
Kommunikation zwischen den Maschinen und dem Gamestate. D.h. Maschinen können via _std::sync::mpsc_ die change rate von oxyge, energy und life im Gamestate verändern.

Die Message-Queue wird in der _tick()_ function des Gamestates abgearbeitet. Alle Maschinen erhalten eine immutable Referenz auf das entsprechende, geteilte Sender-Object.

**Comment by mfloto** [comment]
Depending on #46

**Comment by SanderForGodot** [comment]
SEnder und reciver system

**Comment by mfloto** [comment]
Das werden wir wahrscheinlich doch nicht mit sender und receiver machen, da es schwierig wird die zu serializen.

**Comment by mfloto** [comment]
Sanders Lösung
