### ISSUE TITLE
Tests abändern

### ISSUE THREAD

**Issue by Flippchen** [red-life-project/red-life#68]
- [x] test_load_autosave
- [x] test_load_milestone
- [x] test::addition

**Comment by mfloto** [comment]
Problem bei den saves: Wenn die tests die jeweilige Funktion ausführen, werden die save-files in game/saves gespeichert. Werden die functions von dem laufenden Spiel gecalled, werden die save-files in /saves gespeichert.

**Comment by Flippchen** [comment]
das passt so
kann man mergen. Das ist wegen verschiedenen Working directories..

**Comment by mfloto** [comment]
Ah, okay. Dann waren diese Tests nie broken (außer test_addition).

**Comment by mfloto** [comment]
Die Tests failen doch noch, wenn man cargo test verwendet und die Dateien noch nicht vorhanden sind. Wenn die Tests in der Reihenfolge nacheinander ausführt funktioniert es logischerweise, aber die Tests sollten ja unabhängig sein.

**Comment by mfloto** [comment]
@Nereuxofficial, ich habe jetzt die save-files, die von den tests _test_save_autosave()_ und _test_save_milestone()_ generiert werden, permanent hinzugefügt. Die Test-Funktionen nutzten den game Ordner als root, weshalb die save-files in /game/saves liegen. Du hattest heute noch eine besondere Annotation angesprochen und ich wollte fragen, welche du meinst.

**Comment by Nereuxofficial** [comment]
> @Nereuxofficial, ich habe jetzt die save-files, die von den tests _test_save_autosave()_ und _test_save_milestone()_ generiert werden, permanent hinzugefügt. Die Test-Funktionen nutzten den game Ordner als root, weshalb die save-files in /game/saves liegen. Du hattest heute noch eine besondere Annotation angesprochen und ich wollte fragen, welche du meinst.

Die cfg!(debug) annotation hatte sich dadurch erledigt, dass wir den Standarsave-ordner (vorerst) nutzen

**Comment by mfloto** [comment]
Verstehe, wäre natürlich besser dafür einen test-saves Ordner zu haben

**Comment by Nereuxofficial** [comment]
> Verstehe, wäre natürlich besser dafür einen test-saves Ordner zu haben

Ja ist sogar glaube ich Prio 1 aber erstmal ist Test-passing wichtig
