### ISSUE TITLE
Struct for colors used in project

### ISSUE THREAD

**Issue by mfloto** [red-life-project/red-life#88]
Struct, welches alle Farben hält, die in dem Projekt genutzt werden. Eine Implementation sollte dem von ggez::graphics::types ähneln. Siehe https://docs.rs/ggez/0.8.1/src/ggez/graphics/types.rs.html#273-292 (Das struct müsste empty bleigen können, weil ja eh ein Color object returned werden soll und kein eigenes)

- [x] Struct mit Namen RLColor erstellen
- [x] Farben im Projekt finden und ersetzen

**Comment by Flippchen** [comment]
Farbe 148, 147, 143 bitte hinzufügen
